### ISSUE TITLE
tinyfy.cn不能打开

### ISSUE THREAD

**Issue by uniquejava** [liujinpen/picgo-plugin-compress-tinypng#3]
这个打不开的 cn 地址和官网(.com) 的 https://api.tinify.com 有什么区别?

**Comment by liujinpen** [comment]
https://tinify.cn/是可以打开的，可以在这个网站手动上传图片后下载压缩的图。https://api.tinify.com是api访问的地址，如果要在代码中使用就需要按官方文档调用。

**Comment by uniquejava** [comment]
算了改成另一个插件了,选择使用本地的 imagemin 组件, 离线压缩更快更好.

<img width="663" alt="image" src="https://github.com/liujinpen/picgo-plugin-compress-tinypng/assets/1049271/27aee718-c0d9-4706-bfb6-68aacad122fe">

**Comment by uniquejava** [comment]
> [https://tinify.cn/是可以打开的，可以在这个网站手动上传图片后下载压缩的图。https://api.tinify.com是api访问的地址，如果要在代码中使用就需要按官方文档调用。](https://tinify.cn/%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80%E7%9A%84%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%9C%A8%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E6%89%8B%E5%8A%A8%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87%E5%90%8E%E4%B8%8B%E8%BD%BD%E5%8E%8B%E7%BC%A9%E7%9A%84%E5%9B%BE%E3%80%82https://api.tinify.com%E6%98%AFapi%E8%AE%BF%E9%97%AE%E7%9A%84%E5%9C%B0%E5%9D%80%EF%BC%8C%E5%A6%82%E6%9E%9C%E8%A6%81%E5%9C%A8%E4%BB%A3%E7%A0%81%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%B0%B1%E9%9C%80%E8%A6%81%E6%8C%89%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E8%B0%83%E7%94%A8%E3%80%82)

惊了, 第一次在 github 上抓到活人!!!

**Comment by uniquejava** [comment]
@liujinpen , 谢谢了解了, 原来有中文版的镜像站点, 我一直上的外网

**Comment by liujinpen** [comment]
确实，这个在线的慢很多，之前写的时候没有好用的，现在这个应该好使。

**Comment by liujinpen** [comment]
> > [https://tinify.cn/是可以打开的，可以在这个网站手动上传图片后下载压缩的图。https://api.tinify.com是api访问的地址，如果要在代码中使用就需要按官方文档调用。](https://tinify.cn/%E6%98%AF%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80%E7%9A%84%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%9C%A8%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E6%89%8B%E5%8A%A8%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87%E5%90%8E%E4%B8%8B%E8%BD%BD%E5%8E%8B%E7%BC%A9%E7%9A%84%E5%9B%BE%E3%80%82https://api.tinify.com%E6%98%AFapi%E8%AE%BF%E9%97%AE%E7%9A%84%E5%9C%B0%E5%9D%80%EF%BC%8C%E5%A6%82%E6%9E%9C%E8%A6%81%E5%9C%A8%E4%BB%A3%E7%A0%81%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%B0%B1%E9%9C%80%E8%A6%81%E6%8C%89%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E8%B0%83%E7%94%A8%E3%80%82)
> 
> 惊了, 第一次在 github 上抓到活人!!!

hhhh主要是有的东西吧，代码写完就忘了，有问题也不想回复哈哈哈
